/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ClientLogo = {
  _id: string;
  _type: "clientLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  active?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  authorName: string;
  authorRole?: string;
  company?: string;
  active?: boolean;
  order?: number;
};

export type NewsArticle = {
  _id: string;
  _type: "newsArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category: "Market Insight" | "Career Advice" | "SAP HR" | "Technology" | "Company News";
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "teamMember";
  };
  publishedAt: string;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  bio?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type JobListing = {
  _id: string;
  _type: "jobListing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  module: "SAP FICO" | "SAP CO" | "SAP BPC" | "SAP MM" | "SAP SD" | "SAP WM" | "SAP HCM & SuccessFactors" | "SAP Payroll" | "SAP Basis" | "SAP ABAP" | "SAP S/4HANA" | "Other / Multiple";
  location: string;
  type: "Contract" | "Permanent";
  duration?: string;
  rate?: string;
  description: string;
  publishedAt?: string;
  active?: boolean;
};

export type HeroSlide = {
  _id: string;
  _type: "heroSlide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
  subheading?: string;
  ctaPrimary?: {
    label?: string;
    href?: string;
  };
  ctaSecondary?: {
    label?: string;
    href?: string;
  };
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  active?: boolean;
  order?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stats?: Array<{
    value: string;
    suffix?: string;
    label: string;
    _key: string;
  }>;
  contactEmail?: string;
  contactPhone?: string;
  contactAddress?: string;
  linkedinUrl?: string;
  twitterUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ClientLogo | SanityImageCrop | SanityImageHotspot | Testimonial | NewsArticle | BlockContent | TeamMember | Slug | JobListing | HeroSlide | SiteSettings | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: HERO_SLIDES_QUERY
// Query: *[_type == "heroSlide" && active == true] | order(order asc) {    _id,    heading,    subheading,    ctaPrimary,    ctaSecondary,    image {      asset->{ _id, url, metadata { lqip, dimensions } },      alt,      hotspot,      crop    }  }
export type HERO_SLIDES_QUERYResult = Array<{
  _id: string;
  heading: string;
  subheading: string | null;
  ctaPrimary: {
    label?: string;
    href?: string;
  } | null;
  ctaSecondary: {
    label?: string;
    href?: string;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;
// Variable: JOBS_QUERY
// Query: *[_type == "jobListing" && active == true] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    module,    location,    type,    duration,    rate,    description,    publishedAt  }
export type JOBS_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  module: "Other / Multiple" | "SAP ABAP" | "SAP Basis" | "SAP BPC" | "SAP CO" | "SAP FICO" | "SAP HCM & SuccessFactors" | "SAP MM" | "SAP Payroll" | "SAP S/4HANA" | "SAP SD" | "SAP WM";
  location: string;
  type: "Contract" | "Permanent";
  duration: string | null;
  rate: string | null;
  description: string;
  publishedAt: string | null;
}>;
// Variable: JOBS_PREVIEW_QUERY
// Query: *[_type == "jobListing" && active == true] | order(publishedAt desc) [0...4] {    _id,    title,    "slug": slug.current,    module,    location,    type,    duration,    rate  }
export type JOBS_PREVIEW_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  module: "Other / Multiple" | "SAP ABAP" | "SAP Basis" | "SAP BPC" | "SAP CO" | "SAP FICO" | "SAP HCM & SuccessFactors" | "SAP MM" | "SAP Payroll" | "SAP S/4HANA" | "SAP SD" | "SAP WM";
  location: string;
  type: "Contract" | "Permanent";
  duration: string | null;
  rate: string | null;
}>;
// Variable: NEWS_ARTICLES_QUERY
// Query: *[_type == "newsArticle" && defined(slug.current)] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    category,    publishedAt,    mainImage {      asset->{ _id, url, metadata { lqip, dimensions } },      alt,      hotspot,      crop    },    author->{ name, role }  }
export type NEWS_ARTICLES_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  category: "Career Advice" | "Company News" | "Market Insight" | "SAP HR" | "Technology";
  publishedAt: string;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  author: {
    name: string;
    role: string;
  } | null;
}>;
// Variable: NEWS_PREVIEW_QUERY
// Query: *[_type == "newsArticle" && defined(slug.current)] | order(publishedAt desc) [0...3] {    _id,    title,    "slug": slug.current,    excerpt,    category,    publishedAt,    mainImage {      asset->{ _id, url, metadata { lqip, dimensions } },      alt,      hotspot,      crop    },    author->{ name, role }  }
export type NEWS_PREVIEW_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  category: "Career Advice" | "Company News" | "Market Insight" | "SAP HR" | "Technology";
  publishedAt: string;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  author: {
    name: string;
    role: string;
  } | null;
}>;
// Variable: NEWS_ARTICLE_QUERY
// Query: *[_type == "newsArticle" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    excerpt,    category,    publishedAt,    mainImage {      asset->{ _id, url, metadata { lqip, dimensions } },      alt,      hotspot,      crop    },    author->{ name, role, photo { asset->{ url }, alt } },    body  }
export type NEWS_ARTICLE_QUERYResult = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  category: "Career Advice" | "Company News" | "Market Insight" | "SAP HR" | "Technology";
  publishedAt: string;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  author: {
    name: string;
    role: string;
    photo: {
      asset: {
        url: string | null;
      } | null;
      alt: string | null;
    } | null;
  } | null;
  body: BlockContent | null;
} | null;
// Variable: NEWS_SLUGS_QUERY
// Query: *[_type == "newsArticle" && defined(slug.current)] {    "slug": slug.current  }
export type NEWS_SLUGS_QUERYResult = Array<{
  slug: string;
}>;
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && active == true] | order(order asc) {    _id,    quote,    authorName,    authorRole,    company  }
export type TESTIMONIALS_QUERYResult = Array<{
  _id: string;
  quote: string;
  authorName: string;
  authorRole: string | null;
  company: string | null;
}>;
// Variable: CLIENT_LOGOS_QUERY
// Query: *[_type == "clientLogo" && active == true] | order(order asc) {    _id,    name,    logo {      asset->{ _id, url, metadata { lqip, dimensions } },    },    website  }
export type CLIENT_LOGOS_QUERYResult = Array<{
  _id: string;
  name: string;
  logo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  };
  website: string | null;
}>;
// Variable: TEAM_MEMBERS_QUERY
// Query: *[_type == "teamMember"] | order(order asc) {    _id,    name,    role,    bio,    photo {      asset->{ _id, url, metadata { lqip, dimensions } },      alt,      hotspot,      crop    }  }
export type TEAM_MEMBERS_QUERYResult = Array<{
  _id: string;
  name: string;
  role: string;
  bio: string | null;
  photo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0] {    stats,    contactEmail,    contactPhone,    contactAddress,    linkedinUrl,    twitterUrl  }
export type SITE_SETTINGS_QUERYResult = {
  stats: null;
  contactEmail: null;
  contactPhone: null;
  contactAddress: null;
  linkedinUrl: null;
  twitterUrl: null;
} | {
  stats: Array<{
    value: string;
    suffix?: string;
    label: string;
    _key: string;
  }> | null;
  contactEmail: string | null;
  contactPhone: string | null;
  contactAddress: string | null;
  linkedinUrl: string | null;
  twitterUrl: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"heroSlide\" && active == true] | order(order asc) {\n    _id,\n    heading,\n    subheading,\n    ctaPrimary,\n    ctaSecondary,\n    image {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      alt,\n      hotspot,\n      crop\n    }\n  }\n": HERO_SLIDES_QUERYResult;
    "\n  *[_type == \"jobListing\" && active == true] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    module,\n    location,\n    type,\n    duration,\n    rate,\n    description,\n    publishedAt\n  }\n": JOBS_QUERYResult;
    "\n  *[_type == \"jobListing\" && active == true] | order(publishedAt desc) [0...4] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    module,\n    location,\n    type,\n    duration,\n    rate\n  }\n": JOBS_PREVIEW_QUERYResult;
    "\n  *[_type == \"newsArticle\" && defined(slug.current)] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    category,\n    publishedAt,\n    mainImage {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      alt,\n      hotspot,\n      crop\n    },\n    author->{ name, role }\n  }\n": NEWS_ARTICLES_QUERYResult;
    "\n  *[_type == \"newsArticle\" && defined(slug.current)] | order(publishedAt desc) [0...3] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    category,\n    publishedAt,\n    mainImage {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      alt,\n      hotspot,\n      crop\n    },\n    author->{ name, role }\n  }\n": NEWS_PREVIEW_QUERYResult;
    "\n  *[_type == \"newsArticle\" && slug.current == $slug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    category,\n    publishedAt,\n    mainImage {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      alt,\n      hotspot,\n      crop\n    },\n    author->{ name, role, photo { asset->{ url }, alt } },\n    body\n  }\n": NEWS_ARTICLE_QUERYResult;
    "\n  *[_type == \"newsArticle\" && defined(slug.current)] {\n    \"slug\": slug.current\n  }\n": NEWS_SLUGS_QUERYResult;
    "\n  *[_type == \"testimonial\" && active == true] | order(order asc) {\n    _id,\n    quote,\n    authorName,\n    authorRole,\n    company\n  }\n": TESTIMONIALS_QUERYResult;
    "\n  *[_type == \"clientLogo\" && active == true] | order(order asc) {\n    _id,\n    name,\n    logo {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n    },\n    website\n  }\n": CLIENT_LOGOS_QUERYResult;
    "\n  *[_type == \"teamMember\"] | order(order asc) {\n    _id,\n    name,\n    role,\n    bio,\n    photo {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      alt,\n      hotspot,\n      crop\n    }\n  }\n": TEAM_MEMBERS_QUERYResult;
    "\n  *[_id == \"siteSettings\"][0] {\n    stats,\n    contactEmail,\n    contactPhone,\n    contactAddress,\n    linkedinUrl,\n    twitterUrl\n  }\n": SITE_SETTINGS_QUERYResult;
  }
}
